var searchData=
[
  ['referee_2ecs_379',['Referee.cs',['../_referee_8cs.html',1,'']]],
  ['refereelist_2ecs_380',['RefereeList.cs',['../_referee_list_8cs.html',1,'']]],
  ['refereestochoose_2eg_2ecs_381',['RefereesToChoose.g.cs',['../_referees_to_choose_8g_8cs.html',1,'']]],
  ['refereestochoose_2eg_2ei_2ecs_382',['RefereesToChoose.g.i.cs',['../_referees_to_choose_8g_8i_8cs.html',1,'']]],
  ['refereestochoose_2examl_2ecs_383',['RefereesToChoose.xaml.cs',['../_referees_to_choose_8xaml_8cs.html',1,'']]],
  ['refereesviewmodel_2ecs_384',['RefereesViewModel.cs',['../_referees_view_model_8cs.html',1,'']]],
  ['refereeview_2eg_2ecs_385',['RefereeView.g.cs',['../_referee_view_8g_8cs.html',1,'']]],
  ['refereeview_2eg_2ei_2ecs_386',['RefereeView.g.i.cs',['../_referee_view_8g_8i_8cs.html',1,'']]],
  ['refereeview_2examl_2ecs_387',['RefereeView.xaml.cs',['../_referee_view_8xaml_8cs.html',1,'']]],
  ['removeplayer_2eg_2ecs_388',['RemovePlayer.g.cs',['../_remove_player_8g_8cs.html',1,'']]],
  ['removeplayer_2eg_2ei_2ecs_389',['RemovePlayer.g.i.cs',['../_remove_player_8g_8i_8cs.html',1,'']]],
  ['removeplayer_2examl_2ecs_390',['RemovePlayer.xaml.cs',['../_remove_player_8xaml_8cs.html',1,'']]],
  ['removeplayerfromteamwindow_2eg_2ecs_391',['RemovePlayerFromTeamWindow.g.cs',['../_remove_player_from_team_window_8g_8cs.html',1,'']]],
  ['removeplayerfromteamwindow_2eg_2ei_2ecs_392',['RemovePlayerFromTeamWindow.g.i.cs',['../_remove_player_from_team_window_8g_8i_8cs.html',1,'']]],
  ['removeplayerfromteamwindow_2examl_2ecs_393',['RemovePlayerFromTeamWindow.xaml.cs',['../_remove_player_from_team_window_8xaml_8cs.html',1,'']]],
  ['removereferee_2eg_2ecs_394',['RemoveReferee.g.cs',['../_remove_referee_8g_8cs.html',1,'']]],
  ['removereferee_2eg_2ei_2ecs_395',['RemoveReferee.g.i.cs',['../_remove_referee_8g_8i_8cs.html',1,'']]],
  ['removereferee_2examl_2ecs_396',['RemoveReferee.xaml.cs',['../_remove_referee_8xaml_8cs.html',1,'']]],
  ['removeteam_2eg_2ecs_397',['RemoveTeam.g.cs',['../_remove_team_8g_8cs.html',1,'']]],
  ['removeteam_2eg_2ei_2ecs_398',['RemoveTeam.g.i.cs',['../_remove_team_8g_8i_8cs.html',1,'']]],
  ['removeteam_2examl_2ecs_399',['RemoveTeam.xaml.cs',['../_remove_team_8xaml_8cs.html',1,'']]]
];
